WITH EVENTOS_BASE AS
(
    SELECT
        EVE.EVENTO_ID,
        OCO.OCORRENCIA_ID,
        INP.SE_ID_NORM AS SUBESTACAO_ID,
        INP.AL_ID_NORM AS ALIMENTADOR_ID,
        TO_CHAR(INP.IOP_NUM) AS INSTALACAO,
        EVE.EVE_DATA_INICIO AS DATA_HORA,
        EVE.VIATURA_ID AS VIATURA,

        CASE EVE.EVE_STATUS_EVENTO
            WHEN 'A' THEN 'ABERTO'
            WHEN 'F' THEN 'FECHADO'
        END AS POSICAO_CHAVE,

        NVL(EVE.EVE_QTD_TOTAL, 0) 
        + (SELECT NVL(SUM(EV.EVE_QTD_TOTAL),0) FROM OPERACAO.EVENTOS EV WHERE EV.EVENTO_ID_PAI = EVE.EVENTO_ID) AS IT_AFETADA

    FROM
        OPERACAO.EVENTOS EVE

        INNER JOIN OPERACAO.INSTALACAO_PERMANENTE INP
            ON INP.INSTALACAO_ID = EVE.INSTALACAO_ID

        INNER JOIN OPERACAO.OCORRENCIA PARTITION (PT_ATIVAS) OCO
            ON OCO.OCORRENCIA_ID = EVE.OCORRENCIA_ID

    WHERE
        1 = 1
        AND INP.IOP_NUM IS NOT NULL
        --AND OCO.OCO_NUMERO = 2522
        --AND OCO.OCO_MES = 9
        --AND OCO.OCO_ANO = 2026

    UNION ALL

    SELECT
        ESE.EVENTO_SE_ID AS EVENTO_ID,
        OCO.OCORRENCIA_ID,
        ISE.SE_ID_OPER AS SUBESTACAO_ID,
        NULL AS ALIMENTADOR_ID,
        TO_CHAR(ISE.INT_NUM) AS INSTALACAO,
        ESE.ESE_DATA AS DATA_HORA,
        ESE.VIATURA_ID AS VIATURA,

        CASE ESE.ESE_STATUS_EVENTO
            WHEN 'A' THEN 'ABERTO'
            WHEN 'F' THEN 'FECHADO'
        END AS POSICAO_CHAVE,

        NVL(ESE.ESE_QTD_TOTAL, 0) AS IT_AFETADA

    FROM
        OPERACAO.EVENTOS_SE ESE

        INNER JOIN OPERACAO.ISE_INSTALACAO_OPER_PERMANENTE ISE
            ON ISE.MSLINK = ESE.MSLINK

        INNER JOIN OPERACAO.OCORRENCIA PARTITION (PT_ATIVAS) OCO
            ON OCO.OCORRENCIA_ID = ESE.OCORRENCIA_ID

    WHERE
        1 = 1
        --AND OCO.OCO_NUMERO = 2522
        --AND OCO.OCO_MES = 9
        --AND OCO.OCO_ANO = 2026
),

MOVIMENTOS AS
(
    SELECT
        E.*,

        CASE
            WHEN POSICAO_CHAVE = 'ABERTO'
                THEN IT_AFETADA

            WHEN POSICAO_CHAVE = 'FECHADO'
                THEN -IT_AFETADA

            ELSE 0
        END AS MOVIMENTO_CLIENTES

    FROM
        EVENTOS_BASE E
),

SALDOS AS
(
    SELECT
        M.*,

        SUM(MOVIMENTO_CLIENTES) OVER
        (
            PARTITION BY OCORRENCIA_ID

            ORDER BY
                DATA_HORA,
                EVENTO_ID

            ROWS BETWEEN
                UNBOUNDED PRECEDING
                AND CURRENT ROW
        ) AS SALDO_APOS_EVENTO,

        SUM(MOVIMENTO_CLIENTES) OVER
        (
            PARTITION BY OCORRENCIA_ID

            ORDER BY
                DATA_HORA,
                EVENTO_ID

            ROWS BETWEEN
                UNBOUNDED PRECEDING
                AND 1 PRECEDING
        ) AS SALDO_ANTES_EVENTO,

        LAG(DATA_HORA) OVER
        (
            PARTITION BY OCORRENCIA_ID

            ORDER BY
                DATA_HORA,
                EVENTO_ID
        ) AS DATA_INICIAL_PERIODO

    FROM
        MOVIMENTOS M
),

PERIODOS_EVENTOS AS
(
    SELECT
        EVENTO_ID,
        OCORRENCIA_ID,
        SUBESTACAO_ID,
        ALIMENTADOR_ID,
        INSTALACAO,

        DATA_INICIAL_PERIODO AS DATA_INICIAL,
        DATA_HORA AS DATA_FINAL,

        GREATEST(
            NVL(SALDO_ANTES_EVENTO, 0),
            0
        ) AS CLIENTES_AFETADOS,

        GREATEST(
            NVL(SALDO_APOS_EVENTO, 0),
            0
        ) AS CLIENTES_PENDENTES,

        POSICAO_CHAVE,

        IT_AFETADA AS CLIENTES_MOVIMENTADOS,

        VIATURA

    FROM
        SALDOS

    WHERE
        DATA_INICIAL_PERIODO IS NOT NULL
),

ULTIMO_EVENTO AS
(
    SELECT
        S.*,

        ROW_NUMBER() OVER
        (
            PARTITION BY OCORRENCIA_ID

            ORDER BY
                DATA_HORA DESC,
                EVENTO_ID DESC
        ) AS RN

    FROM
        SALDOS S
),

PERIODO_EM_ABERTO AS
(
    SELECT
        EVENTO_ID,
        OCORRENCIA_ID,
        SUBESTACAO_ID,
        ALIMENTADOR_ID,
        INSTALACAO,

        DATA_HORA AS DATA_INICIAL,
        SYSDATE AS DATA_FINAL,

        GREATEST(
            NVL(SALDO_APOS_EVENTO, 0),
            0
        ) AS CLIENTES_AFETADOS,

        GREATEST(
            NVL(SALDO_APOS_EVENTO, 0),
            0
        ) AS CLIENTES_PENDENTES,

        'EM ABERTO' AS POSICAO_CHAVE,

        0 AS CLIENTES_MOVIMENTADOS,

        VIATURA

    FROM
        ULTIMO_EVENTO

    WHERE
        RN = 1
        AND NVL(SALDO_APOS_EVENTO, 0) > 0
        AND DATA_HORA <= SYSDATE
),

PERIODOS AS
(
    SELECT
        EVENTO_ID,
        OCORRENCIA_ID,
        SUBESTACAO_ID,
        ALIMENTADOR_ID,
        INSTALACAO,
        DATA_INICIAL,
        DATA_FINAL,
        CLIENTES_AFETADOS,
        CLIENTES_PENDENTES,
        POSICAO_CHAVE,
        CLIENTES_MOVIMENTADOS,
        VIATURA

    FROM
        PERIODOS_EVENTOS

    UNION ALL

    SELECT
        EVENTO_ID,
        OCORRENCIA_ID,
        SUBESTACAO_ID,
        ALIMENTADOR_ID,
        INSTALACAO,
        DATA_INICIAL,
        DATA_FINAL,
        CLIENTES_AFETADOS,
        CLIENTES_PENDENTES,
        POSICAO_CHAVE,
        CLIENTES_MOVIMENTADOS,
        VIATURA

    FROM
        PERIODO_EM_ABERTO
),

RESULTADO AS
(
    SELECT
        EVENTO_ID,
        OCORRENCIA_ID,
        SUBESTACAO_ID,
        ALIMENTADOR_ID,
        INSTALACAO,
        DATA_INICIAL,
        DATA_FINAL,
        CLIENTES_AFETADOS,
        CLIENTES_PENDENTES,

        ROUND(
            (DATA_FINAL - DATA_INICIAL) * 1440,
            2
        ) AS DURACAO_MINUTOS,

        ROUND(
            (DATA_FINAL - DATA_INICIAL) * 24,
            6
        ) AS DURACAO_HORAS,

        CASE
            WHEN (DATA_FINAL - DATA_INICIAL) * 1440 > 3
            THEN ROUND(
                (DATA_FINAL - DATA_INICIAL)
                * 24
                * CLIENTES_AFETADOS,
                6
            )

            ELSE 0
        END AS CHI,

        POSICAO_CHAVE,
        CLIENTES_MOVIMENTADOS,
        VIATURA

    FROM
        PERIODOS
),

ULTIMA_LINHA AS
(
    SELECT
        R.*,

        ROW_NUMBER() OVER
        (
            PARTITION BY OCORRENCIA_ID

            ORDER BY
                DATA_FINAL DESC,
                EVENTO_ID DESC
        ) AS RN

    FROM
        RESULTADO R
)

SELECT
    --PER.EVENTO_ID,
    --PER.OCORRENCIA_ID,
    TO_CHAR(OCO.OCO_DATA_NR, 'DD/MM/YYYY HH24:MI:SS') AS DATA_INICIO_OCO,
    OCO.OCO_NUMERO || '-' || OCO.OCO_MES || '-' || OCO.OCO_ANO AS OCORRENCIA,
    UTE.UTE_NOME AS REGIONAL,
    --PER.SUBESTACAO_ID,
    SUB.SUB_NOME AS SUBESTACAO,
    PER.ALIMENTADOR_ID,
    PER.INSTALACAO,

    /**TO_CHAR(
        PER.DATA_INICIAL,
        'DD/MM/YYYY HH24:MI:SS'
    ) AS DATA_INICIAL,

    TO_CHAR(
        PER.DATA_FINAL,
        'DD/MM/YYYY HH24:MI:SS'
    ) AS DATA_FINAL,**/

    --PER.CLIENTES_AFETADOS,
    PER.CLIENTES_PENDENTES
    --PER.DURACAO_MINUTOS,
    --PER.DURACAO_HORAS,
    --PER.CHI,
    --PER.POSICAO_CHAVE,
    --PER.CLIENTES_MOVIMENTADOS,
    --PER.VIATURA
    ,CASE
            WHEN OCO.OCO_STATUS = 'F' THEN 'FINALIZADO'
            WHEN OCO.OCO_STATUS = 'T' THEN 'TRABALHANDO'
            WHEN OCO.OCO_STATUS = 'B' THEN 'ATRIBUÍDA'
            WHEN OCO.OCO_STATUS = 'E' THEN 'EM PREPARAÇÃO'
            WHEN OCO.OCO_STATUS = 'C' THEN 'CANCELADO'
            WHEN OCO.OCO_STATUS = 'V' THEN 'VINCULADO'
            WHEN OCO.OCO_STATUS = 'A' THEN 'EM DESLOCAMENTO'
            WHEN OCO.OCO_STATUS = 'M' THEN 'MANUTENÇÃO'
            ELSE OCO.OCO_STATUS
    END AS STATUS
    ,MTR.MRE_DESCRICAO AS MOTIVO_RECLAMACAO

FROM
    ULTIMA_LINHA PER
    INNER JOIN OPERACAO.OCORRENCIA OCO ON OCO.OCORRENCIA_ID = PER.OCORRENCIA_ID
    INNER JOIN OPERACAO.SUBESTACAO SUB ON SUB.SE_ID = PER.SUBESTACAO_ID
    INNER JOIN OPERACAO.BAIRRO BAI ON BAI.BAIRRO_ID = OCO.BAIRRO_ID
    INNER JOIN OPERACAO.BASE BAS ON BAS.BASE_ID = BAI.BASE_ID
    INNER JOIN OPERACAO.PONTO_APOIO PON ON PON.CODIGO_PA = BAS.CODIGO_PA
    INNER JOIN OPERACAO.UNIDADE_TERRITORIAL UTE ON UTE.REG_ELETRICA_ID = PON.REG_ELETRICA_ID
    INNER JOIN OPERACAO.MOTIVO_DA_RECLAMACAO MTR ON MTR.TB_MT_NR_ID = OCO.TB_MT_NR_ID

WHERE
    RN = 1
ORDER BY
    OCO.OCORRENCIA_ID
