SELECT ID,
       REGIONAL,
       OCORRENCIA,
       AFETACAO,
       INFORMACAO_CONTROLADOR,
       TIPO_DE_NOTA, 
       ROUND(
            (CAST(SYSDATE AS DATE) - CAST(DATA_SOLICITACAO AS DATE)) * 1440
        ,2) AS TEMPO_MINUTOS,
       STATUS,
       PRAZO_COMECIAL
FROM COMUNICA_RECURSOS 
WHERE
    1=1
    AND ((CAST(SYSDATE AS DATE) - CAST(DATA_SOLICITACAO AS DATE)) * 1440) > 10
    AND STATUS IN ('Pendente', 'Aguardando')